import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,copyFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {safePath,validateHtml,validateCatalog,validateRelease,CSP,digest,canonical} from '../scripts/core.mjs';
import {validateRepository} from '../scripts/validate.mjs';
const m={width:960,height:540,slideOrder:['stable-id'],assets:[]};
const html=`<!doctype html><html><head><meta http-equiv="Content-Security-Policy" content="${CSP}"><link rel="stylesheet" href="slides.css"></head><body data-slide-width="960" data-slide-height="540"><section class="slide" id="stable-id"></section><script src="player.js"></script></body></html>`;
test('paths and catalog cannot escape releases or point at missing versions',()=>{for(const p of ['../x','/x','x//y','https://x','x/../../y'])assert(!safePath(p));assert(safePath('assets/abc.webp'));assert.throws(()=>validateCatalog({schemaVersion:1,releases:['x/v1'],current:{x:'x/v2'}}));});
test('editorial markup cannot add script, handlers, external images, frames or CSS imports',()=>{validateHtml(html,m);for(const extra of ['<script>alert(1)</script>','<img src="https://example.org/x">','<div onclick="alert(1)"></div>','<iframe src="https://example.org"></iframe>','<div style="background:url(https://example.org/x)"></div>','<meta http-equiv="refresh" content="0;https://example.org">'])assert.throws(()=>validateHtml(html.replace('</body>',extra+'</body>'),m));assert.throws(()=>validateHtml(html.replace('stable-id','lost-id'),m));});
async function fixture(){const root=await mkdtemp(join(tmpdir(),'accortic-material-test-'));await writeFile(join(root,'index.html'),html);for(const f of ['player.js','slides.css'])await copyFile(new URL('../runtime/'+f,import.meta.url),join(root,f));const files=[];for(const path of ['index.html','player.js','slides.css']){const data=await readFile(join(root,path));files.push({path,bytes:data.length,sha256:digest(data)});}const manifest={...m,schemaVersion:1,materialId:'test',version:1,title:'Test',files,packageHash:digest(canonical(files)),slides:{'stable-id':{title:'Slide',assets:[],tags:[],coverage:{reference:'p.1'}}},approval:{publicDistribution:true,imageOrigin:'teacher-declared-ai-generated',evidence:'Test synthetic'},source:{presentationId:'synthetic',revision:'1',project:{uri:'https://drive.google.com/synthetic'}}};await writeFile(join(root,'material.json'),JSON.stringify(manifest));return {root,manifest};}
test('integrity, arbitrary files and absent public approval stop publication',async()=>{const {root,manifest}=await fixture();try{await validateRelease(root);await writeFile(join(root,'extra.txt'),'secret');await assert.rejects(validateRelease(root),/Extra/);await rm(join(root,'extra.txt'));await writeFile(join(root,'index.html'),html+'changed');await assert.rejects(validateRelease(root),/integrity/);await writeFile(join(root,'index.html'),html);manifest.approval.publicDistribution=false;await writeFile(join(root,'material.json'),JSON.stringify(manifest));await assert.rejects(validateRelease(root),/evidence/);}finally{await rm(root,{recursive:true,force:true});}});
test('existing versions cannot be changed or removed, while catalog rollback remains possible',async()=>{const {root}=await fixture();const repo=await mkdtemp(join(tmpdir(),'accortic-retention-test-'));try{await mkdir(join(repo,'releases/test/v1'),{recursive:true});for(const f of ['index.html','player.js','slides.css','material.json'])await copyFile(join(root,f),join(repo,'releases/test/v1',f));await writeFile(join(repo,'catalog.json'),JSON.stringify({schemaVersion:1,releases:['test/v1'],current:{test:'test/v1'}}));const git=(...args)=>execFileSync('git',args,{cwd:repo,encoding:'utf8'}).trim();git('init');git('add','.');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-m','fixture');const base=git('rev-parse','HEAD');await writeFile(join(repo,'catalog.json'),JSON.stringify({schemaVersion:1,releases:['test/v1'],current:{}}));await validateRepository(repo,base);await writeFile(join(repo,'releases/test/v1/player.js'),'modified');await assert.rejects(validateRepository(repo,base),/Immutable/);}finally{await rm(root,{recursive:true,force:true});await rm(repo,{recursive:true,force:true});}});
